### ISSUE TITLE
Example is not working in typst 0.11

### ISSUE THREAD

**Issue by psads-git** [Marmare314/lemmify#24]
I am using the following code in `typst` 0.11, but getting the error below. Could you please help me? Thanks!

```
#import "@preview/lemmify:0.1.5": *

#example("xxx")[
  #lorem(100)
]
```

```
[2024-03-29T00:26:05Z INFO  typst_ts_compiler::service::diag::console] /x.typ: Compilation failed after 251.111µs
    
error: unknown variable: example
  ┌─ /tmp/x.typ:3:1
  │
3 │ #example("xxx")[
  │  ^^^^^^^
```

**Comment by Marmare314** [comment]
You first need to create the theorem-functions like `example` and then apply the styling:

```typst
#import "@preview/lemmify:0.1.5": *

#let (
  theorem, lemma, corollary,
  remark, proposition, example,
  proof, rules: thm-rules
) = default-theorems("thm-group", lang: "en")

#show: thm-rules

#example(name: "xxx")[
  #lorem(100)
]
```

**Comment by psads-git** [comment]
That is it, @Marmare314. Thanks!
